services:
  db:
    image: mysql:latest
    container_name: my-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: my-db
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
      TZ: Asia/Seoul
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"