spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        show_sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/my-db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379